FROM ubuntu:latest
MAINTAINER Ed
RUN apt update && apt-get upgrade
    apt install -y nano
    apt install -y iproute2
    apt install -y openssh-server
    apt install -y openjdk-11-jdk
    apt install -y jenkins
    apt clean
EXPOSE 80 22 443 8080
CMD ["/var/lib/jenkins", "-D", "FOREGROUND"]
